//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkMultitool {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetworkMultitool.Properties.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Many different tools for working with networks.
        /// </summary>
        internal static string Mod_Description {
            get {
                return ResourceManager.GetString("Mod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Added Split node mode: Select segments and split it to new node.
        ///- Added Unlock segment mode: Unlock building&apos;s segments to change it, or lock segments to prevent delete it.
        ///- Added Invert segment mode: Ability to invert non-symmetrical segments.
        ///- Updated Arrange in line mode: Added overlay of arrange result; Added ability to set arrange direction by choose guide segment; Line calculated more smooth; Height of nodes no more changing; Pillars moving with nodes; Fixed segment directions after move nodes [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Mod_WhatsNewMessage1_1 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add node mode.
        /// </summary>
        internal static string Mode_AddNode {
            get {
                return ResourceManager.GetString("Mode_AddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to add node.
        /// </summary>
        internal static string Mode_AddNode_Info_ClickToAdd {
            get {
                return ResourceManager.GetString("Mode_AddNode_Info_ClickToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select segment to add node.
        /// </summary>
        internal static string Mode_AddNode_Info_SelectToAdd {
            get {
                return ResourceManager.GetString("Mode_AddNode_Info_SelectToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t add node
        ///Too close to nearby node.
        /// </summary>
        internal static string Mode_AddNode_Info_TooCloseNode {
            get {
                return ResourceManager.GetString("Mode_AddNode_Info_TooCloseNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}°.
        /// </summary>
        internal static string Mode_AngleFormat {
            get {
                return ResourceManager.GetString("Mode_AngleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrange at circle mode.
        /// </summary>
        internal static string Mode_ArrangeAtCircle {
            get {
                return ResourceManager.GetString("Mode_ArrangeAtCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrange at line mode.
        /// </summary>
        internal static string Mode_ArrangeAtLine {
            get {
                return ResourceManager.GetString("Mode_ArrangeAtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to complite circle selection.
        /// </summary>
        internal static string Mode_ArrangeCircle_Info_ClickToComplite {
            get {
                return ResourceManager.GetString("Mode_ArrangeCircle_Info_ClickToComplite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to select arrange direction.
        /// </summary>
        internal static string Mode_ArrangeLine_Info_ClickToSelectDirection {
            get {
                return ResourceManager.GetString("Mode_ArrangeLine_Info_ClickToSelectDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select segment to set arrange direction.
        /// </summary>
        internal static string Mode_ArrangeLine_Info_SelectDirection {
            get {
                return ResourceManager.GetString("Mode_ArrangeLine_Info_SelectDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double click on circle center
        ///to change curve direction.
        /// </summary>
        internal static string Mode_Connection_Info_DoubleClickOnCenterToChangeDir {
            get {
                return ResourceManager.GetString("Mode_Connection_Info_DoubleClickOnCenterToChangeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double click to add curve to this line.
        /// </summary>
        internal static string Mode_Connection_Info_DoubleClickToAdd {
            get {
                return ResourceManager.GetString("Mode_Connection_Info_DoubleClickToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double right click to remove this curve.
        /// </summary>
        internal static string Mode_Connection_Info_DoubleClickToRemove {
            get {
                return ResourceManager.GetString("Mode_Connection_Info_DoubleClickToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drag to change radius.
        /// </summary>
        internal static string Mode_Connection_Info_DragToChangeRadius {
            get {
                return ResourceManager.GetString("Mode_Connection_Info_DragToChangeRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drag to move circle.
        /// </summary>
        internal static string Mode_Connection_Info_DragToMove {
            get {
                return ResourceManager.GetString("Mode_Connection_Info_DragToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hold Shift to step 10m
        ///Hold Ctrl to step 1m
        ///Hold Alt to step 0.1m.
        /// </summary>
        internal static string Mode_Connection_Info_RadiusStep {
            get {
                return ResourceManager.GetString("Mode_Connection_Info_RadiusStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hold Ctrl to move X10 slower
        ///Hold Alt to move X100 slower.
        /// </summary>
        internal static string Mode_Connection_Info_SlowMove {
            get {
                return ResourceManager.GetString("Mode_Connection_Info_SlowMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Bezier curve mode.
        /// </summary>
        internal static string Mode_CreateBezier {
            get {
                return ResourceManager.GetString("Mode_CreateBezier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create connection mode.
        /// </summary>
        internal static string Mode_CreateConnection {
            get {
                return ResourceManager.GetString("Mode_CreateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create loop mode.
        /// </summary>
        internal static string Mode_CreateLoop {
            get {
                return ResourceManager.GetString("Mode_CreateLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to change loop.
        /// </summary>
        internal static string Mode_CreateLoop_Info_Change {
            get {
                return ResourceManager.GetString("Mode_CreateLoop_Info_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create parallel mode.
        /// </summary>
        internal static string Mode_CreateParallerl {
            get {
                return ResourceManager.GetString("Mode_CreateParallerl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to apply.
        /// </summary>
        internal static string Mode_Info_Apply {
            get {
                return ResourceManager.GetString("Mode_Info_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to arrange at circle.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_Apply {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Too big angle between nodes
        ///round shape willn&apos;t be perfect.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_BigDelta {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_BigDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double click to reset center position.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_DoubleClickToResetCenter {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_DoubleClickToResetCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double click to reset node position.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_DoubleClickToResetNode {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_DoubleClickToResetNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drag to change radius.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_DragToChangeRadius {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_DragToChangeRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drag to move circle.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_DragToMoveCenter {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_DragToMoveCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drag to move node.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_DragToMoveNode {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_DragToMoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hold Shift to move all nodes
        ///at the same time.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_MoveAll {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_MoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to distribute nodes
        ///evenly between intersections.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_PressToDistributeBetweenIntersections {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_PressToDistributeBetweenIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to distribute nodes evenly on circle.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_PressToDistributeEvenly {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_PressToDistributeEvenly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to distribute
        ///intersections evenly on circle.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_PressToDistributeIntersections {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_PressToDistributeIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to reset parameters.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_PressToReset {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_PressToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong nodes order.
        /// </summary>
        internal static string Mode_Info_ArrangeCircle_WrongOrder {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeCircle_WrongOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to arrange at line.
        /// </summary>
        internal static string Mode_Info_ArrangeLine_Apply {
            get {
                return ResourceManager.GetString("Mode_Info_ArrangeLine_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} or {1} to change all radii.
        /// </summary>
        internal static string Mode_Info_ChangeAllRadius {
            get {
                return ResourceManager.GetString("Mode_Info_ChangeAllRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} or {1} to change both radii.
        /// </summary>
        internal static string Mode_Info_ChangeBothRadius {
            get {
                return ResourceManager.GetString("Mode_Info_ChangeBothRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to switch selected circle.
        /// </summary>
        internal static string Mode_Info_ChangeCircle {
            get {
                return ResourceManager.GetString("Mode_Info_ChangeCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} or {1} to change curve start offset.
        /// </summary>
        internal static string Mode_Info_ChangeOffset {
            get {
                return ResourceManager.GetString("Mode_Info_ChangeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} or {1} to change one radius.
        /// </summary>
        internal static string Mode_Info_ChangeOneRadius {
            get {
                return ResourceManager.GetString("Mode_Info_ChangeOneRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} or {1} to change radius.
        /// </summary>
        internal static string Mode_Info_ChangeRadius {
            get {
                return ResourceManager.GetString("Mode_Info_ChangeRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} or {1} to change offset.
        /// </summary>
        internal static string Mode_Info_ChangeShift {
            get {
                return ResourceManager.GetString("Mode_Info_ChangeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to select first segment.
        /// </summary>
        internal static string Mode_Info_ClickFirstSegment {
            get {
                return ResourceManager.GetString("Mode_Info_ClickFirstSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click on node to change create direction.
        /// </summary>
        internal static string Mode_Info_ClickOnNodeToChangeCreateDir {
            get {
                return ResourceManager.GetString("Mode_Info_ClickOnNodeToChangeCreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to select second segment.
        /// </summary>
        internal static string Mode_Info_ClickSecondSegment {
            get {
                return ResourceManager.GetString("Mode_Info_ClickSecondSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to select node.
        /// </summary>
        internal static string Mode_Info_ClickSelectNode {
            get {
                return ResourceManager.GetString("Mode_Info_ClickSelectNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to change create direction.
        /// </summary>
        internal static string Mode_Info_ClickToChangeCreateDir {
            get {
                return ResourceManager.GetString("Mode_Info_ClickToChangeCreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to unselect node.
        /// </summary>
        internal static string Mode_Info_ClickUnselectNode {
            get {
                return ResourceManager.GetString("Mode_Info_ClickUnselectNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to create connection.
        /// </summary>
        internal static string Mode_Info_Connection_Create {
            get {
                return ResourceManager.GetString("Mode_Info_Connection_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to create.
        /// </summary>
        internal static string Mode_Info_Create {
            get {
                return ResourceManager.GetString("Mode_Info_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move Bezier curve guides to change shape.
        /// </summary>
        internal static string Mode_Info_CreateBezier_MoveGiude {
            get {
                return ResourceManager.GetString("Mode_Info_CreateBezier_MoveGiude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to create loop.
        /// </summary>
        internal static string Mode_Info_Loop_Create {
            get {
                return ResourceManager.GetString("Mode_Info_Loop_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Out of map.
        /// </summary>
        internal static string Mode_Info_OutOfMap {
            get {
                return ResourceManager.GetString("Mode_Info_OutOfMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to switch creation side.
        /// </summary>
        internal static string Mode_Info_Parallel_ChangeShift {
            get {
                return ResourceManager.GetString("Mode_Info_Parallel_ChangeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to create parallel.
        /// </summary>
        internal static string Mode_Info_Parallel_Create {
            get {
                return ResourceManager.GetString("Mode_Info_Parallel_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radius too big.
        /// </summary>
        internal static string Mode_Info_RadiusTooBig {
            get {
                return ResourceManager.GetString("Mode_Info_RadiusTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radius too small.
        /// </summary>
        internal static string Mode_Info_RadiusTooSmall {
            get {
                return ResourceManager.GetString("Mode_Info_RadiusTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select first segment.
        /// </summary>
        internal static string Mode_Info_SelectFirstSegment {
            get {
                return ResourceManager.GetString("Mode_Info_SelectFirstSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select second segment.
        /// </summary>
        internal static string Mode_Info_SelectSecondSegment {
            get {
                return ResourceManager.GetString("Mode_Info_SelectSecondSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select segment.
        /// </summary>
        internal static string Mode_Info_SelectSegment {
            get {
                return ResourceManager.GetString("Mode_Info_SelectSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to apply slope.
        /// </summary>
        internal static string Mode_Info_Slope_Apply {
            get {
                return ResourceManager.GetString("Mode_Info_Slope_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift - X10, Ctrl - X0.1, Alt - X0.01.
        /// </summary>
        internal static string Mode_Info_Step {
            get {
                return ResourceManager.GetString("Mode_Info_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to switch selected offset.
        /// </summary>
        internal static string Mode_Info_SwitchOffset {
            get {
                return ResourceManager.GetString("Mode_Info_SwitchOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hold Shift to underground mode.
        /// </summary>
        internal static string Mode_Info_UndergroundMode {
            get {
                return ResourceManager.GetString("Mode_Info_UndergroundMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong shape.
        /// </summary>
        internal static string Mode_Info_WrongShape {
            get {
                return ResourceManager.GetString("Mode_Info_WrongShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intersect segments mode.
        /// </summary>
        internal static string Mode_IntersectSegment {
            get {
                return ResourceManager.GetString("Mode_IntersectSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edge of one segment is too close to end of second segment.
        /// </summary>
        internal static string Mode_IntersectSegment_Info_EdgeTooClose {
            get {
                return ResourceManager.GetString("Mode_IntersectSegment_Info_EdgeTooClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на These segments don’t intersect.
        /// </summary>
        internal static string Mode_IntersectSegment_Info_NotIntersect {
            get {
                return ResourceManager.GetString("Mode_IntersectSegment_Info_NotIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invert segment mode.
        /// </summary>
        internal static string Mode_InvertSegment {
            get {
                return ResourceManager.GetString("Mode_InvertSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to invert segment.
        /// </summary>
        internal static string Mode_InvertSegment_Info_ClickToReverse {
            get {
                return ResourceManager.GetString("Mode_InvertSegment_Info_ClickToReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select segment to invert it.
        /// </summary>
        internal static string Mode_InvertSegment_Info_SelectToReverse {
            get {
                return ResourceManager.GetString("Mode_InvertSegment_Info_SelectToReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This node can&apos;t be selected
        ///because not connected with others.
        /// </summary>
        internal static string Mode_NodeLine_Info_NotConnected {
            get {
                return ResourceManager.GetString("Mode_NodeLine_Info_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select node to add it to order.
        /// </summary>
        internal static string Mode_NodeLine_Info_SelectNode {
            get {
                return ResourceManager.GetString("Mode_NodeLine_Info_SelectNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}%.
        /// </summary>
        internal static string Mode_PercentagesFormat {
            get {
                return ResourceManager.GetString("Mode_PercentagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}m.
        /// </summary>
        internal static string Mode_RadiusFormat {
            get {
                return ResourceManager.GetString("Mode_RadiusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove node mode.
        /// </summary>
        internal static string Mode_RemoveNode {
            get {
                return ResourceManager.GetString("Mode_RemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not possible to remove this node.
        /// </summary>
        internal static string Mode_RemoveNode_Info_NotAllow {
            get {
                return ResourceManager.GetString("Mode_RemoveNode_Info_NotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set slope mode.
        /// </summary>
        internal static string Mode_SlopeNode {
            get {
                return ResourceManager.GetString("Mode_SlopeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Split node mode.
        /// </summary>
        internal static string Mode_SplitNode {
            get {
                return ResourceManager.GetString("Mode_SplitNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to remove segment from split order.
        /// </summary>
        internal static string Mode_SplitNode_Info_ClickFromOrder {
            get {
                return ResourceManager.GetString("Mode_SplitNode_Info_ClickFromOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to add segment to split order.
        /// </summary>
        internal static string Mode_SplitNode_Info_ClickToOrder {
            get {
                return ResourceManager.GetString("Mode_SplitNode_Info_ClickToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to split node and align to terrain height
        ///Click with Shift to split node and align to source height.
        /// </summary>
        internal static string Mode_SplitNode_Info_ClickToSplit {
            get {
                return ResourceManager.GetString("Mode_SplitNode_Info_ClickToSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not possible split node with only one segment.
        /// </summary>
        internal static string Mode_SplitNode_Info_NotAllowedSplit {
            get {
                return ResourceManager.GetString("Mode_SplitNode_Info_NotAllowedSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not possible add more segments to split order.
        /// </summary>
        internal static string Mode_SplitNode_Info_OrderIsFull {
            get {
                return ResourceManager.GetString("Mode_SplitNode_Info_OrderIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select segments to split.
        /// </summary>
        internal static string Mode_SplitNode_Info_SelectToSplit {
            get {
                return ResourceManager.GetString("Mode_SplitNode_Info_SelectToSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position is too far from source node.
        /// </summary>
        internal static string Mode_SplitNode_Info_TooFar {
            get {
                return ResourceManager.GetString("Mode_SplitNode_Info_TooFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Union nodes mode.
        /// </summary>
        internal static string Mode_UnionNode {
            get {
                return ResourceManager.GetString("Mode_UnionNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to select source node.
        /// </summary>
        internal static string Mode_UnionNode_Info_ClickSource {
            get {
                return ResourceManager.GetString("Mode_UnionNode_Info_ClickSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to unite nodes.
        /// </summary>
        internal static string Mode_UnionNode_Info_ClickUnion {
            get {
                return ResourceManager.GetString("Mode_UnionNode_Info_ClickUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на These nodes have common segment.
        /// </summary>
        internal static string Mode_UnionNode_Info_NoCommon {
            get {
                return ResourceManager.GetString("Mode_UnionNode_Info_NoCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total number of nodes must be no more then 8.
        /// </summary>
        internal static string Mode_UnionNode_Info_Overflow {
            get {
                return ResourceManager.GetString("Mode_UnionNode_Info_Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select source node.
        /// </summary>
        internal static string Mode_UnionNode_Info_SelectSource {
            get {
                return ResourceManager.GetString("Mode_UnionNode_Info_SelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select target node.
        /// </summary>
        internal static string Mode_UnionNode_Info_SelectTarget {
            get {
                return ResourceManager.GetString("Mode_UnionNode_Info_SelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nodes too far from each other.
        /// </summary>
        internal static string Mode_UnionNode_Info_TooFar {
            get {
                return ResourceManager.GetString("Mode_UnionNode_Info_TooFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock segment mode.
        /// </summary>
        internal static string Mode_UnlockSegment {
            get {
                return ResourceManager.GetString("Mode_UnlockSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select segment to
        ///lock or unlock it.
        /// </summary>
        internal static string Mode_UnlockSegment_Info_ChangeLock {
            get {
                return ResourceManager.GetString("Mode_UnlockSegment_Info_ChangeLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to lock this segment.
        /// </summary>
        internal static string Mode_UnlockSegment_Info_ClickToLock {
            get {
                return ResourceManager.GetString("Mode_UnlockSegment_Info_ClickToLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to unlock this segment.
        /// </summary>
        internal static string Mode_UnlockSegment_Info_ClickToUnlock {
            get {
                return ResourceManager.GetString("Mode_UnlockSegment_Info_ClickToUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activation shortcuts.
        /// </summary>
        internal static string Settings_ActivationShortcuts {
            get {
                return ResourceManager.GetString("Settings_ActivationShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto hide modes panel.
        /// </summary>
        internal static string Settings_AutoHideModePanel {
            get {
                return ResourceManager.GetString("Settings_AutoHideModePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modes&apos; common shortcuts.
        /// </summary>
        internal static string Settings_CommonShortcuts {
            get {
                return ResourceManager.GetString("Settings_CommonShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Panel columns count.
        /// </summary>
        internal static string Settings_PanelColumns {
            get {
                return ResourceManager.GetString("Settings_PanelColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play audio and visual effects.
        /// </summary>
        internal static string Settings_PlayEffects {
            get {
                return ResourceManager.GetString("Settings_PlayEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max Segment Length.
        /// </summary>
        internal static string Settings_SegmentLength {
            get {
                return ResourceManager.GetString("Settings_SegmentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply mode action.
        /// </summary>
        internal static string Settings_Shortcut_Apply {
            get {
                return ResourceManager.GetString("Settings_Shortcut_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease circle start offset.
        /// </summary>
        internal static string Settings_Shortcut_DecreaseOffset {
            get {
                return ResourceManager.GetString("Settings_Shortcut_DecreaseOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease one radius.
        /// </summary>
        internal static string Settings_Shortcut_DecreaseOneRadius {
            get {
                return ResourceManager.GetString("Settings_Shortcut_DecreaseOneRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease radii.
        /// </summary>
        internal static string Settings_Shortcut_DecreaseRadii {
            get {
                return ResourceManager.GetString("Settings_Shortcut_DecreaseRadii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease radius.
        /// </summary>
        internal static string Settings_Shortcut_DecreaseRadius {
            get {
                return ResourceManager.GetString("Settings_Shortcut_DecreaseRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease offset.
        /// </summary>
        internal static string Settings_Shortcut_DecreaseShift {
            get {
                return ResourceManager.GetString("Settings_Shortcut_DecreaseShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distribute nodes evenly between intersections.
        /// </summary>
        internal static string Settings_Shortcut_DistributeBetweenIntersections {
            get {
                return ResourceManager.GetString("Settings_Shortcut_DistributeBetweenIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distribute nodes evenly on circle.
        /// </summary>
        internal static string Settings_Shortcut_DistributeEvenly {
            get {
                return ResourceManager.GetString("Settings_Shortcut_DistributeEvenly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distribute intersections evenly on circle.
        /// </summary>
        internal static string Settings_Shortcut_DistributeIntersections {
            get {
                return ResourceManager.GetString("Settings_Shortcut_DistributeIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase circle start offset.
        /// </summary>
        internal static string Settings_Shortcut_IncreaseOffset {
            get {
                return ResourceManager.GetString("Settings_Shortcut_IncreaseOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase one radius.
        /// </summary>
        internal static string Settings_Shortcut_IncreaseOneRadius {
            get {
                return ResourceManager.GetString("Settings_Shortcut_IncreaseOneRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase radii.
        /// </summary>
        internal static string Settings_Shortcut_IncreaseRadii {
            get {
                return ResourceManager.GetString("Settings_Shortcut_IncreaseRadii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase radius.
        /// </summary>
        internal static string Settings_Shortcut_IncreaseRadius {
            get {
                return ResourceManager.GetString("Settings_Shortcut_IncreaseRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase offset.
        /// </summary>
        internal static string Settings_Shortcut_IncreaseShift {
            get {
                return ResourceManager.GetString("Settings_Shortcut_IncreaseShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch creation side.
        /// </summary>
        internal static string Settings_Shortcut_InvertShift {
            get {
                return ResourceManager.GetString("Settings_Shortcut_InvertShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to default circle.
        /// </summary>
        internal static string Settings_Shortcut_ResetArrangeCircle {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ResetArrangeCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch loop direction.
        /// </summary>
        internal static string Settings_Shortcut_SwitchIsLoop {
            get {
                return ResourceManager.GetString("Settings_Shortcut_SwitchIsLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch selected offset.
        /// </summary>
        internal static string Settings_Shortcut_SwitchOffset {
            get {
                return ResourceManager.GetString("Settings_Shortcut_SwitchOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch selected circle.
        /// </summary>
        internal static string Settings_Shortcut_SwitchSelect {
            get {
                return ResourceManager.GetString("Settings_Shortcut_SwitchSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slope unit of measurement.
        /// </summary>
        internal static string Settings_SlopeUnit {
            get {
                return ResourceManager.GetString("Settings_SlopeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Degrees.
        /// </summary>
        internal static string Settings_SlopeUnitDegrees {
            get {
                return ResourceManager.GetString("Settings_SlopeUnitDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Percentages.
        /// </summary>
        internal static string Settings_SlopeUnitPercentages {
            get {
                return ResourceManager.GetString("Settings_SlopeUnitPercentages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to remove.
        /// </summary>
        internal static string Tool_RemoveNode_Info_ClickToRemove {
            get {
                return ResourceManager.GetString("Tool_RemoveNode_Info_ClickToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select node to remove it.
        /// </summary>
        internal static string Tool_RemoveNode_Info_Select {
            get {
                return ResourceManager.GetString("Tool_RemoveNode_Info_Select", resourceCulture);
            }
        }
    }
}
